// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleM-TbNZXdj2AQqgEU8jh8yJK9Br9MSo',
    appId: '1:88516661803:android:7cfec74654caed6b0e506e',
    messagingSenderId: '88516661803',
    projectId: 'whatbytes-task-app-68831',
    storageBucket: 'whatbytes-task-app-68831.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuqctfk1WpgIUbp6hmnCCn9f1tsRFhFzc',
    appId: '1:88516661803:ios:cc4487ffbec6858f0e506e',
    messagingSenderId: '88516661803',
    projectId: 'whatbytes-task-app-68831',
    storageBucket: 'whatbytes-task-app-68831.firebasestorage.app',
    androidClientId:
        '88516661803-4drr5ae0riks8p3rdmkc9h1a0cp1ahe1.apps.googleusercontent.com',
    iosClientId:
        '88516661803-i8iqa3nr1b5juv83hdtjjha986doc8u1.apps.googleusercontent.com',
    iosBundleId: 'com.whatbytes.taskflow',
  );
}
